/**
 * @param {string} s
 * @param {string} t
 * @returns {character}
 * @readonly You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘. Note: You may assume that at most one additional character can be added to t.
 */

function spotTheDifference(s, t) {
  let hashMap = {};
  for (let i = 0; i < s.length; i++) {
    hashMap[s[i]] = hashMap[s[i]] + 1 || 1;
  }
  for (let j = 0; j < t.length; j++) {
    if (!hashMap[t[j]]) return t[j];
    hashMap[t[j]]--;
  }
  return ' ';
}

let = s1 = 'foobar';
let t1 = 'barfoot';
let s2 = 'coding';
let t2 = 'ingcod';
console.log(spotTheDifference(s1, t1));
console.log(spotTheDifference(s2, t2));
